export const taskList = [
  {
    id: 0,
    title: "Create Home screen ERP Website",
    description: "",
    tags: ["DevOps", "BackEnd"],
    priority: "Low",
    project: "Company",
    progress: 40,
    assignees: [1],
    status: "inprogress",
    dueDate: "2025-05-06",
  },
  {
    id: 1,
    title: "Desk Research about market of fitness",
    description: "",
    tags: ["BackEnd"],
    priority: "High",
    project: "Outsource",
    progress: 0,
    assignees: [2],
    status: "ongoing",
    dueDate: "2025-05-12",
  },
  {
    id: 2,
    title: "Create Log in/ Log out ERP Website",
    description: "",
    tags: ["Research", "BackEnd"],
    priority: "Medium",
    project: "Outsource",
    progress: 100,
    assignees: [1, 2],
    status: "completed",
    dueDate: "2025-05-01",
  },
  {
    id: 3,
    title: "Create Walkthrough screens",
    description: "",
    tags: ["Task"],
    priority: "Medium",
    project: "Company",
    progress: 100,
    assignees: [1],
    status: "completed",
    dueDate: "2025-05-03",
  },
  {
    id: 4,
    title: "Plan to interview 15 users",
    description: "",
    tags: ["Research"],
    priority: "High",
    project: "Company",
    progress: 100,
    assignees: [2, 3],
    status: "completed",
    dueDate: "2025-05-09",
  },
  {
    id: 5,
    title: "Plan to survey 80 users",
    description: "",
    tags: ["Research", "Task"],
    priority: "Medium",
    project: "Company",
    progress: 40,
    assignees: [1, 2],
    status: "inprogress",
    dueDate: "2025-05-09",
  },
  {
    id: 6,
    title: "Conduct analysis of Godomo's competitors",
    description: "",
    tags: ["Research"],
    priority: "Low",
    project: "Company",
    progress: 90,
    assignees: [2],
    status: "inprogress",
    dueDate: "2025-05-07",
  },
  {
    id: 7,
    title: "3 Demo concepts for Home page",
    description: "",
    tags: ["Deploy", "Task"],
    priority: "Medium",
    project: "Company",
    progress: 100,
    assignees: [1, 2],
    status: "completed",
    dueDate: "2025-05-11",
  },
  {
    id: 8,
    title: "Synthesize data from interviews and surveys",
    description: "",
    tags: ["Research", "Task", "BackEnd"],
    priority: "Low",
    project: "Company",
    progress: 100,
    assignees: [3],
    status: "completed",
    dueDate: "2025-05-14",
  },
];
